import axios from 'axios';
// @ts-ignore
import { RAPIDAPI_API_KEY, TARGET_CITY } from '@env';

export const searchLocation = async () =>
  await axios.request({
    method: 'GET',
    url: 'https://tripadvisor16.p.rapidapi.com/api/v1/restaurant/searchLocation',
    params: { query: TARGET_CITY },
    headers: {
      'X-RapidAPI-Key': RAPIDAPI_API_KEY,
      'X-RapidAPI-Host': 'tripadvisor16.p.rapidapi.com',
    },
  });

export const searchRestaurants = async (locationId: number, page: number) =>
  await axios.request({
    method: 'GET',
    url: 'https://tripadvisor16.p.rapidapi.com/api/v1/restaurant/searchRestaurants',
    params: { locationId, page },
    headers: {
      'X-RapidAPI-Key': RAPIDAPI_API_KEY,
      'X-RapidAPI-Host': 'tripadvisor16.p.rapidapi.com',
    },
  });

export const getRestaurantDetails = async (restaurantsId: string) =>
  await axios.request({
    method: 'GET',
    url: 'https://tripadvisor16.p.rapidapi.com/api/v1/restaurant/getRestaurantDetails',
    params: { restaurantsId, currencyCode: 'USD' },
    headers: {
      'X-RapidAPI-Key': RAPIDAPI_API_KEY,
      'X-RapidAPI-Host': 'tripadvisor16.p.rapidapi.com',
    },
  });

const getRestaurantDetailsSampleResponse = {
  status: true,
  message: 'Success',
  timestamp: 1687185968592,
  data: {
    location: {
      location_id: '1008614',
      name: 'Mabruk',
      latitude: '19.096565',
      longitude: '72.85387',
      num_reviews: '707',
      timezone: 'Asia/Kolkata',
      location_string: 'Mumbai, Maharashtra',
      awards: [],
      doubleclick_zone: 'as.india.mumbai',
      preferred_map_engine: 'default',
      raw_ranking: '4.921928405761719',
      ranking_geo: 'Mumbai',
      ranking_geo_id: '304554',
      ranking_position: '1',
      ranking_denominator: '9288',
      ranking_category: 'restaurant',
      ranking: '#1 of 14,842 places to eat in Mumbai',
      distance: null,
      distance_string: null,
      bearing: null,
      rating: '5.0',
      is_closed: false,
      open_now_text: 'Open Now',
      is_long_closed: false,
      price_level: '$$$$',
      price: '$1,100 - $2,500',
      neighborhood_info: [{ location_id: '15621466', name: 'Vile Parle East' }],
      description:
        'Mabruk - The Mediterranean restaurant, This Lebanese offing sets the mood with its casual low seating on a wooden deck and a spectacular view of the lagoon area, the pillar less clear-to-the sky dome as well as the other restaurants. Combining the sophistication and subtleties of Mediterranean cuisines with the exotic ingredients of the Middle and Far East. MABRUK, the Mediterranean, nine-time award winner for the "Best Lebanese Restaurant" by Times Food Guide offers rich Lebanese culture with soulful Mediterranean sounds and mouth-watering cuisine conjured by Chef Jihad. Chef Jihad creates a repertoire of traditional mezzeh\'s complimented by carefully picked soups, main courses and desserts, creating an awe-inspiring array of flavors, textures and aromas.',
      web_url: 'https://www.tripadvisor.com/Restaurant_Review-g304554-d1008614-Reviews-Mabruk-Mumbai_Maharashtra.html',
      write_review: 'https://www.tripadvisor.com/UserReview-g304554-d1008614-Mabruk-Mumbai_Maharashtra.html',
      ancestors: [
        { subcategory: [{ key: 'city', name: 'City' }], name: 'Mumbai', abbrv: null, location_id: '304554' },
        { subcategory: [{ key: 'state', name: 'State' }], name: 'Maharashtra', abbrv: null, location_id: '297648' },
        { subcategory: [{ key: 'country', name: 'Country' }], name: 'India', abbrv: null, location_id: '293860' },
      ],
      category: { key: 'restaurant', name: 'Restaurant' },
      subcategory: [{ key: 'sit_down', name: 'Sit down' }],
      parent_display_name: 'Mumbai',
      is_jfy_enabled: false,
      nearest_metro_station: [],
      phone: '+91 86574 11561',
      website: 'http://www.saharastar.com/dining/mabruk-mediterranean-restaurant.html',
      email: 'info@saharastar.com',
      address_obj: { street1: 'Domestic Airport Western Express Highway', street2: 'Hotel Sahara Star', city: 'Mumbai', state: 'Maharashtra', country: 'India', postalcode: '400099' },
      address: 'Domestic Airport Western Express Highway Hotel Sahara Star, Mumbai 400099 India',
      hours: {
        week_ranges: [
          [{ open_time: 1140, close_time: 1425 }],
          [{ open_time: 1140, close_time: 1425 }],
          [{ open_time: 1140, close_time: 1425 }],
          [{ open_time: 1140, close_time: 1425 }],
          [{ open_time: 1140, close_time: 1425 }],
          [{ open_time: 1140, close_time: 1425 }],
          [{ open_time: 1140, close_time: 1425 }],
        ],
        timezone: 'Asia/Kolkata',
      },
      is_candidate_for_contact_info_suppression: false,
      cuisine: [
        { key: '10626', name: 'Lebanese' },
        { key: '10649', name: 'Mediterranean' },
        { key: '10687', name: 'Middle Eastern' },
        { key: '10665', name: 'Vegetarian Friendly' },
        { key: '10697', name: 'Vegan Options' },
        { key: '10751', name: 'Halal' },
        { key: '10992', name: 'Gluten Free Options' },
      ],
      dietary_restrictions: [
        { key: '10665', name: 'Vegetarian Friendly' },
        { key: '10697', name: 'Vegan Options' },
        { key: '10751', name: 'Halal' },
        { key: '10992', name: 'Gluten Free Options' },
      ],
      photo: {
        id: '220718948',
        caption: 'Inside View of Lagoon',
        published_date: '2016-09-30T09:50:38-0400',
        helpful_votes: '6',
        is_blessed: false,
        uploaded_date: '2016-09-30T09:50:38-0400',
        images: {
          small: { url: 'https://media-cdn.tripadvisor.com/media/photo-l/0d/27/e7/64/inside-view-of-lagoon.jpg', width: '150', height: '150' },
          thumbnail: { url: 'https://media-cdn.tripadvisor.com/media/photo-t/0d/27/e7/64/inside-view-of-lagoon.jpg', width: '50', height: '50' },
          original: { url: 'https://media-cdn.tripadvisor.com/media/photo-o/0d/27/e7/64/inside-view-of-lagoon.jpg', width: '1024', height: '683' },
          large: { url: 'https://media-cdn.tripadvisor.com/media/photo-s/0d/27/e7/64/inside-view-of-lagoon.jpg', width: '550', height: '366' },
          medium: { url: 'https://media-cdn.tripadvisor.com/media/photo-f/0d/27/e7/64/inside-view-of-lagoon.jpg', width: '250', height: '167' },
        },
      },
      tags: null,
      display_hours: [{ days: 'Sun - Sat', times: ['7:00 PM - 11:45 PM'] }],
    },
    hours: {
      openStatus: 'OPEN',
      openStatusText: 'Open Now',
      hoursTodayText: 'Hours Today: 7:00 PM - 11:45 PM',
      currentHoursText: '7:00 PM - 11:45 PM',
      allOpenHours: [{ days: 'Sun - Sat', times: ['7:00 PM - 11:45 PM'] }],
      addHoursLink: { url: '/UpdateListing-d1008614#Hours-only', text: '+ Add hours' },
    },
    ownerStatus: { isVerified: true, isMemberOwner: false, isUserInCountry: false },
    ownerLikelihood: { isOwner: false, likelihood: 'LOW' },
    overview: {
      name: 'Mabruk, India',
      detailId: 1008614,
      geo: 'Mumbai, India',
      geoId: 304554,
      isOwner: false,
      links: { warUrl: '/UserReviewEdit-g304554-d1008614-Mabruk-Mumbai_Maharashtra.html', addPhotoUrl: '/PostPhotos-g304554-d1008614', ownerAddPhotoUrl: '/ManagePhotos-d1008614-Mabruk' },
      location: {
        latitude: 19.096565,
        longitude: 72.85387,
        directionsUrl:
          'ZG9YX2h0dHBzOi8vbWFwcy5nb29nbGUuY29tL21hcHM/c2FkZHI9JmRhZGRyPURvbWVzdGljK0FpcnBvcnQrV2VzdGVybitFeHByZXNzK0hpZ2h3YXkrSG90ZWwrU2FoYXJhK1N0YXIlMkMrTXVtYmFpKzQwMDA5OStJbmRpYUAxOS4wOTY1NjUsNzIuODUzODdfVHhM',
        landmark: '<b>2.0 miles</b> from Juhu Beach',
        neighborhood: 'Vile Parle East',
      },
      contact: {
        address: 'Domestic Airport Western Express Highway Hotel Sahara Star, Mumbai 400099 India',
        email: 'info@saharastar.com',
        phone: '+91 86574 11561',
        website: 'U0V4X2h0dHA6Ly93d3cuc2FoYXJhc3Rhci5jb20vZGluaW5nL21hYnJ1ay1tZWRpdGVycmFuZWFuLXJlc3RhdXJhbnQuaHRtbF9rcUQ=',
      },
      rating: {
        primaryRanking: { rank: 1, totalCount: 8597, category: 'Restaurants', geo: 'Mumbai', url: '/Restaurants-g304554-Mumbai_Maharashtra.html' },
        secondaryRanking: null,
        primaryRating: 5,
        reviewCount: 707,
        ratingQuestions: [
          { name: 'Food', rating: 45, icon: 'restaurants' },
          { name: 'Service', rating: 50, icon: 'bell' },
          { name: 'Value', rating: 45, icon: 'wallet-fill' },
          { name: 'Atmosphere', rating: 50, icon: 'ambience' },
        ],
      },
      tags: {
        reviewSnippetSections: [
          {
            heading: 'Lebanese, Mediterranean, Middle Eastern, Vegetarian Friendly, Vegan Options',
            reviewSnippets: [
              { text: '&#x201c;Mezze Platter, <b>Tagine</b> Khador and Baklava were delicious.&#x201d;', reviewLink: '/ShowUserReviews-g304554-d1008614-r868212279-Mabruk-Mumbai_Maharashtra.html' },
              {
                text: '&#x201c;Authentic <b>Mediterranean food</b> with wonderful ambience and staff&#x201d;',
                reviewLink: '/ShowUserReviews-g304554-d1008614-r832842269-Mabruk-Mumbai_Maharashtra.html',
              },
              {
                text: '&#x201c;... us he suggested mezze platter and <b>lamb</b> dish it was amazing...a must visit...&#x201d;',
                reviewLink: '/ShowUserReviews-g304554-d1008614-r882045875-Mabruk-Mumbai_Maharashtra.html',
              },
              { text: '&#x201c;Must visiting place for slow cooked <b>lamb</b> meat and Baklava.&#x201d;', reviewLink: '/ShowUserReviews-g304554-d1008614-r854504839-Mabruk-Mumbai_Maharashtra.html' },
            ],
          },
        ],
      },
      detailCard: {
        tagTexts: {
          priceRange: { tagCategoryId: 240, tags: [{ tagId: 10954, tagValue: 'Fine Dining' }] },
          cuisines: {
            tagCategoryId: 231,
            tags: [
              { tagId: 10626, tagValue: 'Lebanese' },
              { tagId: 10649, tagValue: 'Mediterranean' },
              { tagId: 10687, tagValue: 'Middle Eastern' },
            ],
          },
          dietaryRestrictions: {
            tagCategoryId: 285,
            tags: [
              { tagId: 10665, tagValue: 'Vegetarian Friendly' },
              { tagId: 10697, tagValue: 'Vegan Options' },
              { tagId: 10751, tagValue: 'Halal' },
              { tagId: 10992, tagValue: 'Gluten Free Options' },
            ],
          },
          meals: {
            tagCategoryId: 233,
            tags: [
              { tagId: 10599, tagValue: 'Dinner' },
              { tagId: 10949, tagValue: 'Drinks' },
            ],
          },
          features: {
            tagCategoryId: 234,
            tags: [
              { tagId: 10602, tagValue: 'Reservations' },
              { tagId: 10854, tagValue: 'Parking Available' },
              { tagId: 10861, tagValue: 'Wheelchair Accessible' },
              { tagId: 10863, tagValue: 'Full Bar' },
              { tagId: 10601, tagValue: 'Takeout' },
              { tagId: 10852, tagValue: 'Seating' },
              { tagId: 10856, tagValue: 'Validated Parking' },
              { tagId: 10857, tagValue: 'Valet Parking' },
              { tagId: 10862, tagValue: 'Serves Alcohol' },
              { tagId: 10865, tagValue: 'Accepts American Express' },
              { tagId: 10866, tagValue: 'Accepts Mastercard' },
              { tagId: 10867, tagValue: 'Accepts Visa' },
              { tagId: 10870, tagValue: 'Free Wifi' },
              { tagId: 11780, tagValue: 'Accepts Credit Cards' },
              { tagId: 16547, tagValue: 'Table Service' },
              { tagId: 21379, tagValue: 'Non-smoking restaurants' },
            ],
          },
          establishmentType: { tagCategoryId: 230, tags: [{ tagId: 10591, tagValue: 'Restaurants' }] },
        },
        numericalPrice: '$13 - $31',
        improveListingUrl: '/ImproveListing-d1008614.html',
        updateListingUrl: '/ManageListing-g304554-d1008614-Mabruk-Mumbai_Maharashtra.html',
        restaurantOwner: { text: null, tooltip: null, trackingItemName: '' },
      },
    },
  },
};

// 304554(mumbai) result
const searchRestaurantsSampleResponse = {
  data: {
    status: true,
    message: 'Success',
    timestamp: 1687185376084,
    data: {
      totalRecords: '13939',
      totalPages: 465,
      data: [
        {
          restaurantsId: 'Restaurant_Review-g304554-d1008614-Reviews-Mabruk-Mumbai_Maharashtra',
          heroImgUrl: 'https://media-cdn.tripadvisor.com/media/photo-s/0b/55/a9/05/mabruk-the-mediterranean.jpg',
          heroImgRawHeight: 367,
          heroImgRawWidth: 550,
          squareImgUrl: '',
          squareImgRawLength: 0,
          locationId: 1008614,
          name: 'Mabruk',
          averageRating: 5,
          userReviewCount: 707,
          currentOpenStatusCategory: 'OPEN',
          currentOpenStatusText: 'Open Now',
          establishmentTypeAndCuisineTags: ['Lebanese', 'Mediterranean'],
          priceTag: '$$$$',
          offers: { slot1Offer: null, slot2Offer: null },
          hasMenu: false,
          menuUrl: null,
          isDifferentGeo: false,
          parentGeoName: 'Mumbai',
          distanceTo: '',
          reviewSnippets: {
            reviewSnippetsList: [
              {
                reviewText: '&#x201c;... us he suggested mezze platter and <b>lamb</b> dish it was amazing...a must visit...&#x201d;',
                reviewUrl: '/ShowUserReviews-g304554-d1008614-r882045875-Mabruk-Mumbai_Maharashtra.html',
              },
              {
                reviewText: '&#x201c;Mezze Platter, <b>Tagine</b> Khador and Baklava were delicious.&#x201d;',
                reviewUrl: '/ShowUserReviews-g304554-d1008614-r868212279-Mabruk-Mumbai_Maharashtra.html',
              },
            ],
          },
          awardInfo: null,
          isLocalChefItem: false,
          isPremium: false,
          isStoryboardPublished: false,
          hasRestaurantSpecialOffer: false,
        },
        {
          restaurantsId: 'Restaurant_Review-g304554-d2034920-Reviews-Namak-Mumbai_Maharashtra',
          heroImgUrl: 'https://media-cdn.tripadvisor.com/media/photo-s/0b/58/1d/b7/namak.jpg',
          heroImgRawHeight: 378,
          heroImgRawWidth: 550,
          squareImgUrl: '',
          squareImgRawLength: 0,
          locationId: 2034920,
          name: 'Namak',
          averageRating: 5,
          userReviewCount: 637,
          currentOpenStatusCategory: 'OPEN',
          currentOpenStatusText: 'Open Now',
          establishmentTypeAndCuisineTags: ['Indian'],
          priceTag: '$$$$',
          offers: { slot1Offer: null, slot2Offer: null },
          hasMenu: false,
          menuUrl: null,
          isDifferentGeo: false,
          parentGeoName: 'Mumbai',
          distanceTo: '',
          reviewSnippets: {
            reviewSnippetsList: [
              {
                reviewText: '&#x201c;Bravo to the entire crew...We particularly enjoyed the <b>Biryani</b> and Dal Makhni.&#x201d;',
                reviewUrl: '/ShowUserReviews-g304554-d2034920-r888056544-Namak-Mumbai_Maharashtra.html',
              },
              {
                reviewText: '&#x201c;<b>Best indian</b> cousin experience&#x201d;',
                reviewUrl: '/ShowUserReviews-g304554-d2034920-r867336464-Namak-Mumbai_Maharashtra.html',
              },
            ],
          },
          awardInfo: null,
          isLocalChefItem: false,
          isPremium: false,
          isStoryboardPublished: false,
          hasRestaurantSpecialOffer: false,
        },
        {
          restaurantsId: 'Restaurant_Review-g304554-d10338075-Reviews-EAST_EAST_ASIAN_SPICE_TRAIL-Mumbai_Maharashtra',
          heroImgUrl: 'https://media-cdn.tripadvisor.com/media/photo-s/0d/13/75/e0/live-teppanyaki-counter.jpg',
          heroImgRawHeight: 366,
          heroImgRawWidth: 550,
          squareImgUrl: '',
          squareImgRawLength: 0,
          locationId: 10338075,
          name: 'EAST-EAST ASIAN SPICE TRAIL',
          averageRating: 5,
          userReviewCount: 568,
          currentOpenStatusCategory: 'OPEN',
          currentOpenStatusText: 'Open Now',
          establishmentTypeAndCuisineTags: ['Asian', 'Chinese'],
          priceTag: '$$$$',
          offers: { slot1Offer: null, slot2Offer: null },
          hasMenu: false,
          menuUrl: null,
          isDifferentGeo: false,
          parentGeoName: 'Mumbai',
          distanceTo: '',
          reviewSnippets: {
            reviewSnippetsList: [
              {
                reviewText: '&#x201c;Fantastic <b>sushi</b> amazing food overall super experience!&#x201d;',
                reviewUrl: '/ShowUserReviews-g304554-d10338075-r889374806-EAST_EAST_ASIAN_SPICE_TRAIL-Mumbai_Maharashtra.html',
              },
              {
                reviewText: '&#x201c;... with our 2 year old and ordered Cantonese bai fan and Vietnamese fried <b>tofu</b>.&#x201d;',
                reviewUrl: '/ShowUserReviews-g304554-d10338075-r871162391-EAST_EAST_ASIAN_SPICE_TRAIL-Mumbai_Maharashtra.html',
              },
            ],
          },
          awardInfo: null,
          isLocalChefItem: false,
          isPremium: false,
          isStoryboardPublished: false,
          hasRestaurantSpecialOffer: false,
        },
        {
          restaurantsId: 'Restaurant_Review-g304554-d2034948-Reviews-The_Earth_Plate-Mumbai_Maharashtra',
          heroImgUrl: 'https://media-cdn.tripadvisor.com/media/photo-s/0d/6c/8a/fc/salad-counter.jpg',
          heroImgRawHeight: 367,
          heroImgRawWidth: 550,
          squareImgUrl: '',
          squareImgRawLength: 0,
          locationId: 2034948,
          name: 'The Earth Plate',
          averageRating: 5,
          userReviewCount: 773,
          currentOpenStatusCategory: 'OPEN',
          currentOpenStatusText: 'Open Now',
          establishmentTypeAndCuisineTags: ['Indian', 'Chinese'],
          priceTag: '$$$$',
          offers: { slot1Offer: null, slot2Offer: null },
          hasMenu: false,
          menuUrl: null,
          isDifferentGeo: false,
          parentGeoName: 'Mumbai',
          distanceTo: '',
          reviewSnippets: {
            reviewSnippetsList: [
              {
                reviewText: '&#x201c;<b>Family dinner</b>&#x201d;',
                reviewUrl: '/ShowUserReviews-g304554-d2034948-r872075762-The_Earth_Plate-Mumbai_Maharashtra.html',
              },
              {
                reviewText: '&#x201c;The Agra <b>Chaat</b>, Chinese Counter and North Indian Counter were my favourites.&#x201d;',
                reviewUrl: '/ShowUserReviews-g304554-d2034948-r849978502-The_Earth_Plate-Mumbai_Maharashtra.html',
              },
            ],
          },
          awardInfo: null,
          isLocalChefItem: false,
          isPremium: false,
          isStoryboardPublished: false,
          hasRestaurantSpecialOffer: false,
        },
      ],
    },
  },
};
// mumbai result
const searchLocationSampleResponse = {
  data: {
    status: true,
    message: 'Success',
    timestamp: 1687185077964,
    data: [
      {
        locationId: 304554,
        documentId: 'loc;304554;g304554',
        propertyId: 304554,
        localizedName: 'Mumbai',
        localizedAdditionalNames: { longOnlyHierarchy: 'Maharashtra, India, Asia' },
        streetAddress: { street1: '' },
        locationV2: {
          placeType: 'CITY',
          names: { longOnlyHierarchyTypeaheadV2: 'Maharashtra, India' },
          vacationRentalsRoute: { url: '/VacationRentals-g304554-Reviews-Mumbai_Maharashtra-Vacation_Rentals.html' },
        },
        placeType: 'CITY',
        latitude: 18.936844,
        longitude: 72.8291,
        isGeo: true,
        thumbnail: {
          photoSizeDynamic: {
            maxWidth: 5328,
            maxHeight: 3000,
            urlTemplate: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/4e/55/e6/chhatrapati-shivaji-terminus.jpg?w={width}&h={height}&s=1',
          },
        },
      },
    ],
  },
};
